### ISSUE TITLE
easyhls_rtsp创建的文件没有写文件权限

### ISSUE THREAD

**Issue by kent-wu** [EasyDarwin/EasyHLS#3]
我执行命令easyhls_rtsp -c 3 -C 0 -v 3 -t 5 -d /dm/live/ -n 123456 -u rtsp://**.**.**.***:554/123456? -U http://127.0.0.1/，发现一直能拿到视频流，但是没有生成相应的m3u8和ts文件。
创建的新文件夹的权限是dr-xr--r-t，没有写权限，所以就没有文件生成。
请协助调查问题，谢谢

**Comment by babosa** [comment]
新版本已修复此问题，通过chown命令将目标根目录赋值给非root用户，然后执行easyhls_rtsp命令即可！
